# -*- coding: utf-8 -*-
"""codigoBase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bVG02N-63jlB2PJozEhCIQf1e1cXOtS
"""

import pandas as pd
import plotly.express as px
import streamlit as st 


#streamlit run codigoBase.py

#LENDO O DATASET
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

#MELHORANDO O NOME DAS COLUNAS DA TABELA
df = df.rename(columns={'newDeaths': 'Novos óbitos','newCases': 'Novos casos','deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes','totalCases_per_100k_inhabitants':'Casos por 100 mil habitantes'})

#SELECÃO DO ESTADO
estados = list(df['state'].unique())
state = st.sidebar.selectbox('Selecione a UF:', estados)

#SELEÇÃO DA COLUNA
#column ='Casos por 100 mil habitantes'
colunas = ['Novos óbitos','Novos casos','Óbitos por 100 mil habitantes','Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Selecione o tipo de informação:', colunas)

#SELEÇÃO DAS LINHAS QUE PERTECEM AO ESTADO 
df = df[df['state'] == state]

fig = px.line(df, x="date", y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})


st.title('DADOS COVID - BRASIL')
st.write('Nesta aplicação, é possível selecionar a UF e o tipo de informação relacionada aos casos de Covid-19. Utilize o menu lateral para selecionar as preferências de visualização gráfica.')

st.plotly_chart(fig, use_container_width=True)

st.caption('Fonte dos dados: https://github.com/wcota/covid19br')